### ISSUE TITLE
Implement swipe/button liking system

### ISSUE THREAD

**Issue by matthewdking** [facn2/path-18-app#28]
#6 

### Acceptance criteria
- [x] swipe functionality - [react-swing](https://www.npmjs.com/package/react-swing)
- [x] buttons for like and dislike
- [x] adding results to database

### Comments/resources
+ technical spike on Redux actions, reducers and database

**Comment by finnhodgkin** [comment]
https://medium.com/@rajaraodv/a-guide-for-building-a-react-redux-crud-app-7fe0b8943d0f

**Comment by veredrec** [comment]
Yesterday we made the basic query for our database with adding the user input from the `addCareer` form to the database. 
After reading the medium article :arrow_up: which is really good :+1:  I am wondering if we should change our way of querying the db or not. 
It seems to me like maybe it adds unnecessary steps by using more containers and components with states and actions to store and update the database, unless it has significant advantages which I am not aware of or unless this is the more professional way of doing it :cactus: 
Thoughts?
