### ISSUE TITLE
Research/technical spike - redux store with database

### ISSUE THREAD

**Issue by matthewdking** [facn2/path-18-app#35]
We did some quite weird stuff in the previous project. I would really like to research a much cleaner way to do this so we can use redux properly. Maybe if we find some useful docs/articles post them in the comments :taco:

**Comment by matthewdking** [comment]
Depending on how we are doing this we may need to save previous versions of the redux store specific to each user in the database. This might involved having some sort of new schema?

**Comment by matthewdking** [comment]
So my understanding so far is...
- user logs in
- action sends a request to database to get the relevant data
- puts the data into the redux store

I'm unsure of how often we are saving data to the database but this is my general understanding of some of the flow. :taco:

**Comment by finnhodgkin** [comment]
Here's an example of a promise-based thunk from [here](https://medium.com/react-native-training/redux-4-ways-95a130da0cdc):
```js
import { FETCHING_DATA, FETCHING_DATA_SUCCESS, FETCHING_DATA_FAILURE } from './constants'
import getPeople from './api'

export function getData() {
  return {
    type: FETCHING_DATA
  }
}

export function getDataSuccess(data) {
  return {
    type: FETCHING_DATA_SUCCESS,
    data,
  }
}

export function getDataFailure() {
  return {
    type: FETCHING_DATA_FAILURE
  }
}

export function fetchData() {
  return (dispatch) => {
    dispatch(getData())
    getPeople()
      .then((data) => {
        dispatch(getDataSuccess(data))
      })
      .catch((err) => console.log('err:', err))
  }
}
```
I'm guessing they meant to dispatch getDataFail instead of console.log but :man_shrugging:

**Comment by finnhodgkin** [comment]
His recommendation is to use redux-promise for everything but really large applications.
