### ISSUE TITLE
Colour theme

### ISSUE THREAD

**Issue by matthewdking** [facn2/path-18-app#46]
I'm styling at the moment and I'm fairly certain some of it looks rubbish cos the colours are random (mostly looks rubbish cos my css skills are lacking :see_no_evil:). I think we should decide on a colour scheme now! Any ideas @veredrec @finnhodgkin

**Comment by veredrec** [comment]
I have 3 suggestions (but we can find many more!): 

https://coolors.co/e4572e-17bebb-ffc914-2e282a-76b041
https://coolors.co/56e39f-59c9a5-5b6c5d-3b2c35-2a1f2d
https://coolors.co/2d728f-3b8ea5-f5ee9e-f49e4c-ab3428

Thoughts? Other suggestions?

**Comment by matthewdking** [comment]
After messing around with colours I am leaning towards one main colour maybe blue and maybe a lighter version for highlighting. Then everything else sort of white or grey colours to keep everything nice and clean.

So far I have used:
- white
- gainsboro (borders)
- darkgrey (box shadows) - I think I used dim grey somewhere as well
- black (text)
- steelblue (navbar)


So maybe need to add in another version of blue to highlight things but this is my first stab. Any thoughts on this?

**Comment by finnhodgkin** [comment]
Trying to make the whole app with only named colours? :laughing:

At least for now I think that colour selection looks good. We may be a little in danger of going too far in the opposite direction from the old design - where before it was childish it's now a little overly cold and functional. I guess it depends on the card designs and the welcome screen though :woman_shrugging:

**Comment by matthewdking** [comment]
I want it cold and hard and uninviting :expressionless:

**Comment by veredrec** [comment]
Cold :snowman_with_snow: is good!
