### ISSUE TITLE
Server becoming difficult without handlebars/react

### ISSUE THREAD

**Issue by finnhodgkin** [facn2/path-18-app#57]
The `add-career` form is getting out of hand, it's 300 lines of very repetitive html that would be way more maintainable and readable as a handlebars template. Also looking forward we're going to hit a bunch of problems when we add an `edit-career` route: some form of templating will be necessary to show the list of careers to edit and also to build an edit form for each career. 

I think rather than attempting to push on with vanilla html until it gets too hard, we should just move the admin section to handlebars now. 

Sorry to keep ping-ponging on this! :ping_pong:

**Comment by matthewdking** [comment]
Yeah this makes sense I guess! I'm happy to go ahead and do this now :+1:
